edit:
  active: true
  scheduling: 60
  status: publish
  mapping_title:
    source: field
    value: title
  mapping_description:
    source: custom
  mapping_content:
    source: custom
  mapping_author:
    source: custom
  mapping_thumbnail:
    source: field
  mapping_taxonomies:
    source: field
