edit:
  active: true
  scheduling: 60
  status: publish
  item_title:
    source: field
    value: title
  item_description:
    source: custom
  item_content:
    source: custom
  item_author:
    source: custom
  item_thumbnail:
    source: field
  item_taxonomies:
    source: field
