enabled: true
scheduling: 60
status: publish
query: false
item_title: '@ron:title'
item_description: '@ron:sub_title'
item_content: '@ron:content'
item_authors: '@ron:author'
item_taxonomies: '@ron:taggable'
item_thumbnail: '@ron:intro_image'
