edit:
  active: true
  scheduling: 60
  status: publish
  content_title:
    source: field
    value: title
  content_description:
    source: custom
  content_content:
    source: custom
  content_author:
    source: custom
  content_thumbnail:
    source: field
  content_taxonomies:
    source: field
